128.199.75.218:
  repository: https://github.com/BukhariMuslim/MasterClean-Care-Web
  deploy_path: /var/www/masterclean
  branch: master
  domain: masterclean-care.tk
  port: 2222
  user: root
  identityFile: ~
  forwardAgent: true
  multiplexing: true